name: Call Reusable Workflow

on:
  push:
    branches:
      - master

jobs:
  call_reusable_workflow:
    uses: clouddrove/github-shared-workflows/.github/workflows/docker-scanner.yml@master
    with:
      severity: HIGH,CRITICAL # Pass valid severity levels
      name: hello
       
       
