name: Call Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call_reusable_workflow:
    uses: Ammaan123/reusable-workflow-repo/.github/workflows/reusable.yml@main
    with:
      name: World
      greeting: Hi
