name: Trivy Vulnerability Scan

on:
  push:

jobs:
  build-amd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for AMD
        run: |
          docker build --platform linux/amd64 -t my-local-image:amd64 .

  build-arm:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for ARM
        run: |
          docker build --platform linux/arm64 -t my-local-image:arm64 .

  create-manifest:
    runs-on: ubuntu-latest
    needs: [build-amd, build-arm]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create and push Docker manifest
        run: |
          docker manifest create my-local-image:latest \
            my-local-image:amd64 \
            my-local-image:arm64
          docker manifest push my-local-image:latest

      - name: Download latest manifest image
        run: |
          docker pull my-local-image:latest

      - name: Upload manifest image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: manifest-image
          path: /home/runner/.docker/manifests
