name: Docker Build and TFLint Check

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t amaan9656/fine:amd64 -f Dockerfile .

      - name: Push Docker image
        run: docker push amaan9656/fine:amd64

      - name: Clean up image
        run: docker rmi amaan9656/fine:amd64
