name: Trivy Vulnerability Scan

on:
  push:

jobs:
  build-amd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "Qqpp001@123" | docker login -u "amaan9656" --password-stdin

      - name: Build Docker image for AMD
        run: |
          docker build --platform linux/amd64 -t amaan9656/fine:amd64 -f Dockerfile .
      
      - name: Push Docker image for AMD
        run: |
          docker push amaan9656/fine:amd64

  build-arm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "Qqpp001@123" | docker login -u "amaan9656" --password-stdin

      - name: Build Docker image for ARM
        run: |
          docker build --platform linux/arm64 -t amaan9656/fine:arm64 -f Dockerfile .
      
      - name: Push Docker image for ARM
        run: |
          docker push amaan9656/fine:arm64

  create-manifest:
    runs-on: ubuntu-latest
    needs: [build-amd, build-arm]

    steps:
      - name: Log in to Docker Hub
        run: echo "Qqpp001@123" | docker login -u "amaan9656" --password-stdin

      - name: Create Docker manifest
        run: |
          docker manifest create amaan9656/fine:latest \
            amaan9656/fine:amd64 \
            amaan9656/fine:arm64 --amend

      - name: Push Docker manifest
        run: |
          docker manifest push amaan9656/fine:latest

      - name: Delete AMD image
        run: |
          docker rmi amaan9656/fine:amd64

      - name: Delete ARM image
        run: |
          docker rmi amaan9656/fine:arm64
