name: Trivy Vulnerability Scan

on:
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-local-image:latest .

     - name: 'Trivy Scan for Vulnerabilities'
    run: |
    # Install Trivy
    sudo apt-get update && sudo apt-get install -y curl
    curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.45.0/trivy_0.45.0_Linux-64bit.deb -o trivy.deb
    sudo dpkg -i trivy.deb
    rm -f trivy.deb

    # Scan the Docker image for vulnerabilities
    trivy image --exit-code 1 --no-progress $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}
